CREATE TABLE t_pays(
   id          INTEGER  NOT NULL PRIMARY KEY
  ,nationalite VARCHAR(17)
  ,libelle     VARCHAR(36) NOT NULL
);
INSERT INTO t_pays(id,nationalite,libelle) VALUES (1,'afghane','Afghanistan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (2,'sudafricaine','Afrique du Sud');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (3,'albanaise','Albanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (4,'algérienne','Algérie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (5,'allemande','Allemagne');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (6,'andorrane','Andorre');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (7,'angolaise','Angola');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (8,'antiguayenne','Antigua-et-Barbuda');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (9,'saoudienne','Arabie saoudite');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (10,'argentine','Argentine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (11,'arménienne','Arménie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (12,'australienne','Australie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (13,'autrichienne','Autriche');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (14,'azerbaïdjanaise','Azerbaïdjan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (15,'bahaméenne','Bahamas');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (16,'bahreïnienne','Bahreïn');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (17,'bangladaise','Bangladesh');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (18,'barbadienne','Barbade');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (19,'belge','Belgique');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (20,'bélizienne','Belize');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (22,'bhoutanaise','Bhoutan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (24,'birmane','Birmanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (23,'biélorusse','Biélorussie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (25,'bolivienne','Bolivie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (26,'bosnienne','Bosnie-Herzégovine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (27,'botswanaise','Botswana');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (29,'brunéienne','Brunei');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (28,'brésilienne','Brésil');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (30,'bulgare','Bulgarie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (31,'burkinabé','Burkina');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (32,'burundaise','Burundi');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (21,'béninoise','Bénin');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (33,'cambodgienne','Cambodge');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (34,'camerounaise','Cameroun');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (35,'canadienne','Canada');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (36,'cap-verdienne','Cap-Vert');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (144,'centrafricaine','Centrafrique');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (37,'chilienne','Chili');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (38,'chinoise','Chine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (39,'chypriote','Chypre');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (40,'colombienne','Colombie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (41,'comorienne','Comores');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (42,'congolaise','Congo');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (43,'nord-coréenne','Corée du Nord');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (44,'sud-coréenne','Corée du Sud');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (45,'costaricienne','Costa Rica');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (47,'croate','Croatie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (48,'cubaine','Cuba');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (46,'ivoirienne','Côte d''Ivoire');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (49,'danoise','Danemark');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (50,'djiboutienne','Djibouti');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (51,'dominiquaise','Dominique');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (52,'egyptienne','Egypte');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (53,'emirienne','Emirats arabes unis');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (54,'equatorienne','Equateur');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (55,'erythréenne','Erythrée');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (56,'espagnole','Espagne');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (57,'estonienne','Estonie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (58,'américaine','Etats-Unis');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (59,'ethiopienne','Ethiopie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (60,'fidjienne','Fidji');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (61,'finlandaise','Finlande');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (62,'française','France');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (63,'gabonaise','Gabon');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (64,'gambienne','Gambie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (66,'ghanéenne','Ghana');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (68,'grenadienne','Grenade');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (67,'grecque','Grèce');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (69,'guatémaltèque','Guatemala');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (70,'guinéenne','Guinée');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (71,'equatoguinéenne','Guinée équatoriale');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (72,'bissaoguinéenne','Guinée-Bissao');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (73,'guyanienne','Guyana');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (65,'géorgienne','Géorgie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (74,'haïtienne','Haïti');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (75,'hondurienne','Honduras');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (77,'hongroise','Hongrie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (79,'indienne','Inde');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (80,'indonésienne','Indonésie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (81,'irakienne','Irak');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (82,'iranienne','Iran');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (83,'irlandaise','Irlande');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (84,'islandaise','Islande');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (85,'israélienne','Israël');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (86,'italienne','Italie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (87,'jamaïquaine','Jamaïque');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (88,'japonaise','Japon');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (90,'jordanienne','Jordanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (89,'palestinienne','Jérusalem - Territoires palestiniens');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (91,'kazakhstanais','Kazakhstan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (92,'kényane','Kenya');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (93,'kirghize','Kirghizstan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (94,'kiribatienne','Kiribati');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (198,'kosovare','Kosovo');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (95,'koweïtienne','Koweït');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (96,'laotienne','Laos');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (97,'lesothienne','Lesotho');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (98,'lettone','Lettonie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (99,'libanaise','Liban');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (100,'libérienne','Liberia');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (101,'libyenne','Libye');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (102,'liechtensteinoise','Liechtenstein');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (103,'lituanienne','Lituanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (104,'luxembourgeoise','Luxembourg');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (105,'macédonienne','Macédoine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (106,'malgache','Madagascar');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (107,'malaisienne','Malaisie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (108,'malawienne','Malawi');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (109,'maldivienne','Maldives');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (110,'malienne','Mali');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (111,'maltaise','Malte');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (112,'marocaine','Maroc');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (113,'marshallaise','Marshall');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (114,'mauricienne','Maurice');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (115,'mauritanienne','Mauritanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (116,'mexicaine','Mexique');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (117,'micronésienne','Micronésie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (118,'moldave','Moldavie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (119,'monégasque','Monaco');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (120,'mongole','Mongolie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (197,'monténégrine','Monténégro');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (121,'mozambicaine','Mozambique');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (122,'namibienne','Namibie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (123,'nauruane','Nauru');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (125,'nicaraguayenne','Nicaragua');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (126,'nigérienne','Niger');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (127,'nigériane','Nigeria');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (128,'norvégienne','Norvège');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (129,'néo-zélandaise','Nouvelle-Zélande');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (124,'népalaise','Népal');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (130,'omanaise','Oman');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (131,'ougandaise','Ouganda');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (132,'ouzbèke','Ouzbékistan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (133,'pakistanaise','Pakistan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (134,'palaoise','Palaos');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (135,'panaméenne','Panama');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (136,'papouasienne','Papouasie-Nouvelle-Guinée');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (137,'paraguayenne','Paraguay');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (138,'néerlandaise','Pays-Bas');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (140,'philippine','Philippines');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (141,'polonaise','Pologne');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (142,'portugaise','Portugal');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (139,'péruvienne','Pérou');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (143,'qatarienne','Qatar');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (148,'roumaine','Roumanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (149,'britannique','Royaume-Uni');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (150,'russe','Russie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (151,'rwandaise','Rwanda');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (146,'dominicaine','République dominicaine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (145,'congolaise (RDC)','République démocratique du Congo');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (147,'tchèque','République tchèque');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (152,'christophienne','Saint-Christophe-et-Niévès');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (154,'marinaise','Saint-Marin');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (155,NULL,'Saint-Siège');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (156,'vincentaise','Saint-Vincent-et-les Grenadines');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (153,'lucienne','Sainte-Lucie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (157,'salomonaise','Salomon');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (158,'salvadorienne','Salvador');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (159,'samoene','Samoa');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (160,'santoméenne','Sao Tomé-et-Principe');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (162,'serbe','Serbie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (163,'seychelloise','Seychelles');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (164,'sierraléonaise','Sierra Leone');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (165,'singapourienne','Singapour');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (166,'slovaque','Slovaquie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (167,'slovène','Slovénie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (168,'somalienne','Somalie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (169,'soudanaise','Soudan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (170,'srilankaise','Sri Lanka');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (172,'suisse','Suisse');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (173,'surinamaise','Suriname');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (171,'suédoise','Suède');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (174,'swazie','Swaziland');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (175,'syrienne','Syrie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (161,'sénégalaise','Sénégal');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (176,'tadjike','Tadjikistan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (178,'tanzanienne','Tanzanie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (177,'taïwanaise','Taïwan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (179,'tchadienne','Tchad');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (180,'thaïlandaise','Thaïlande');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (181,'timoraise','Timor oriental');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (182,'togolaise','Togo');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (183,'tongienne','Tonga');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (184,'trinidadienne','Trinité-et-Tobago');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (185,'tunisienne','Tunisie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (186,'turkmène','Turkménistan');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (187,'turque','Turquie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (188,'tuvaluane','Tuvalu');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (189,'ukrainienne','Ukraine');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (190,'uruguayenne','Uruguay');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (191,'vanuataise','Vanuatu');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (192,'vénézuélienne','Venezuela');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (193,'vietnamienne','Viêt Nam');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (194,'yéménite','Yémen');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (195,'zambienne','Zambie');
INSERT INTO t_pays(id,nationalite,libelle) VALUES (196,'zimbabwéenne','Zimbabwe');
